### ISSUE TITLE
Running every minute.

### ISSUE THREAD

**Issue by daveferrara1** [coppit/docker-no-ip#3]
I seem to be logging an attempt to update every minute. 

I have my interval set to: 

`INTERVAL='20m'`

Latest version of docker. Ubuntu 16.04.

**Comment by coppit** [comment]
Sorry for the delay.

In your log, does it say "Updating every 20 minutes via /dev/eth0 with NAT enabled."?

If so, I think you might be confused. It prints the status every minute, but it only updates the DNS every 20 minutes.

**Comment by coppit** [comment]
Closing. Please reopen if I'm wrong.
